/** @type {import('stylelint').Config} */
export default {
	extends: [
		'stylelint-config-standard-scss',
		'stylelint-config-html/astro',
		'stylelint-config-clean-order',
	],
	rules: {
		/* 💡 Buenas prácticas */
		'no-empty-source': true,
		'no-descending-specificity': null, // útil si usas Tailwind o BEM
		'selector-class-pattern': [
			'^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(--[a-z0-9]([-]?[a-z0-9]+)*)?$',
		],
		'block-no-empty': true,
		/* 📐 Orden de propiedades (usado desde clean-order) */
		'order/properties-order': [
			// Posicionamiento y box model
			'position',
			'top',
			'right',
			'bottom',
			'left',
			'z-index',
			// Flex / Grid
			'display',
			'flex-direction',
			'flex-wrap',
			'justify-content',
			'align-items',
			'align-content',
			'order',
			'flex',
			'flex-grow',
			'flex-shrink',
			'flex-basis',
			'grid-template-columns',
			'grid-template-rows',
			'grid-area',
			// Box model
			'box-sizing',
			'width',
			'min-width',
			'max-width',
			'height',
			'min-height',
			'max-height',
			'margin',
			'margin-top',
			'margin-right',
			'margin-bottom',
			'margin-left',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			// Border
			'border',
			'border-top',
			'border-right',
			'border-bottom',
			'border-left',
			'border-radius',
			// Background
			'background',
			'background-color',
			'background-image',
			'background-size',
			'background-position',
			'background-repeat',
			// Typography
			'color',
			'font',
			'font-size',
			'font-weight',
			'font-family',
			'line-height',
			'letter-spacing',
			'text-align',
			'text-decoration',
			'text-transform',
			'white-space',
			// Effects
			'box-shadow',
			'opacity',
			'transform',
			'transition',
			'animation',
			// Misc
			'cursor',
			'visibility',
			'overflow',
			'overflow-x',
			'overflow-y',
		],
		/* ⚠️ Desactiva reglas que chocan con Prettier */
		// 'declaration-block-trailing-semicolon': null,
		// 'block-closing-brace-newline-after': null,
		// 'value-list-comma-newline-after': null,
	},
	ignoreFiles: [
		'**/*.min.css',
		'src/legacy/**/*.css',
		'vendor/**',
		'src/assets/',
	],
};
